FROM arm64v8/python:3-alpine

WORKDIR /app

COPY requirements.txt .
COPY static static
COPY templates templates
COPY main.py .
COPY lib.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
