# Generated by Django 5.1.7 on 2025-07-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_taskexecutionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlineserver',
            options={'verbose_name': 'Outline', 'verbose_name_plural': 'Outline'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('access_server', 'Can view public status')], 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='wireguardserver',
            options={'verbose_name': 'Wireguard', 'verbose_name_plural': 'Wireguard'},
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user'], name='vpn_accessl_user_05a541_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['server'], name='vpn_accessl_server_0865e6_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['timestamp'], name='vpn_accessl_timesta_480a45_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['action', 'timestamp'], name='vpn_accessl_action_898948_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['task_id'], name='vpn_taskexe_task_id_e7e101_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['created_at'], name='vpn_taskexe_created_b458ed_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['status'], name='vpn_taskexe_status_2f0769_idx'),
        ),
    ]
