# Generated by Django 5.1.7 on 2025-07-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_acllink_last_access_time'),
        ('vpn', '0003_alter_outlineserver_options_alter_server_options_and_more'),
    ]

    operations = [
    ]
