# Generated by Django 5.1.7 on 2025-07-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_userstatistics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userstatistics',
            new_name='vpn_usersta_user_id_512036_idx',
            old_name='vpn_usersta_user_id_1c7cd0_idx',
        ),
        migrations.RenameIndex(
            model_name='userstatistics',
            new_name='vpn_usersta_updated_5ac650_idx',
            old_name='vpn_usersta_updated_8e6e9b_idx',
        ),
    ]
