# Generated by Django 5.1.7 on 2025-07-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_accesslog_acl_link_id'),
        ('vpn', '0006_rename_vpn_usersta_user_id_1c7cd0_idx_vpn_usersta_user_id_512036_idx_and_more'),
    ]

    operations = [
    ]
