# Generated by Django 5.1.7 on 2025-07-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_merge_20250721_1345'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='vpn_accessl_acl_lin_9f3bc5_idx',
            old_name='vpn_accessl_acl_lin_b23c6e_idx',
        ),
    ]
