# Generated by Django 5.1.7 on 2025-07-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_rename_vpn_accessl_acl_lin_b23c6e_idx_vpn_accessl_acl_lin_9f3bc5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayCoreServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpn.server')),
                ('api_address', models.CharField(help_text='Xray Core API address (e.g., http://127.0.0.1:8080)', max_length=255)),
                ('api_port', models.IntegerField(default=8080, help_text='API port for management interface')),
                ('api_token', models.CharField(blank=True, help_text='API authentication token', max_length=255)),
                ('server_address', models.CharField(help_text='Server address for clients to connect', max_length=255)),
                ('server_port', models.IntegerField(default=443, help_text='Server port for client connections')),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('shadowsocks', 'Shadowsocks'), ('trojan', 'Trojan')], default='vless', help_text='Primary protocol for this server', max_length=20)),
                ('security', models.CharField(choices=[('none', 'None'), ('tls', 'TLS'), ('reality', 'REALITY'), ('xtls', 'XTLS')], default='tls', help_text='Security layer configuration', max_length=20)),
                ('transport', models.CharField(choices=[('tcp', 'TCP'), ('ws', 'WebSocket'), ('http', 'HTTP/2'), ('grpc', 'gRPC'), ('quic', 'QUIC')], default='tcp', help_text='Transport protocol', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Complete Xray configuration in JSON format')),
                ('panel_url', models.CharField(blank=True, help_text='Web panel URL if using 3X-UI or similar management panel', max_length=255)),
                ('panel_username', models.CharField(blank=True, help_text='Panel admin username', max_length=100)),
                ('panel_password', models.CharField(blank=True, help_text='Panel admin password', max_length=100)),
            ],
            options={
                'verbose_name': 'Xray Core Server',
                'verbose_name_plural': 'Xray Core Servers',
            },
            bases=('vpn.server',),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('Outline', 'Outline'), ('Wireguard', 'Wireguard'), ('xray_core', 'Xray Core')], editable=False, max_length=50),
        ),
    ]
