# Generated by Django 5.1.7 on 2025-07-28 22:34

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_xraycoreserver_alter_server_server_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='api_address',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='api_port',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='api_token',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='config_json',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='panel_password',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='panel_url',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='panel_username',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='security',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='server_address',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='server_port',
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='transport',
        ),
        migrations.AddField(
            model_name='xraycoreserver',
            name='default_protocol',
            field=models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('trojan', 'Trojan'), ('shadowsocks', 'Shadowsocks')], default='vless', help_text='Default protocol for new inbounds', max_length=20),
        ),
        migrations.AddField(
            model_name='xraycoreserver',
            name='enable_stats',
            field=models.BooleanField(default=True, help_text='Enable traffic statistics tracking'),
        ),
        migrations.AddField(
            model_name='xraycoreserver',
            name='grpc_address',
            field=models.CharField(default='127.0.0.1', help_text='Xray Core gRPC API address', max_length=255),
        ),
        migrations.AddField(
            model_name='xraycoreserver',
            name='grpc_port',
            field=models.IntegerField(default=10085, help_text='gRPC API port (usually 10085)'),
        ),
        migrations.CreateModel(
            name='XrayInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Unique identifier for this inbound', max_length=100)),
                ('port', models.IntegerField(help_text='Port to listen on')),
                ('listen', models.CharField(default='0.0.0.0', help_text='IP address to listen on', max_length=255)),
                ('protocol', models.CharField(choices=[('vless', 'VLESS'), ('vmess', 'VMess'), ('trojan', 'Trojan'), ('shadowsocks', 'Shadowsocks')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this inbound for new users by default')),
                ('network', models.CharField(choices=[('tcp', 'TCP'), ('ws', 'WebSocket'), ('http', 'HTTP/2'), ('grpc', 'gRPC'), ('quic', 'QUIC')], default='tcp', max_length=20)),
                ('security', models.CharField(choices=[('none', 'None'), ('tls', 'TLS'), ('reality', 'REALITY')], default='none', max_length=20)),
                ('server_address', models.CharField(blank=True, help_text='Public server address for client connections (if different from listen address)', max_length=255)),
                ('ss_method', models.CharField(blank=True, default='chacha20-ietf-poly1305', help_text='Shadowsocks encryption method', max_length=50)),
                ('ss_password', models.CharField(blank=True, help_text='Shadowsocks password (for single-user mode)', max_length=255)),
                ('tls_cert_file', models.CharField(blank=True, max_length=255)),
                ('tls_key_file', models.CharField(blank=True, max_length=255)),
                ('tls_alpn', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('stream_settings', models.JSONField(blank=True, default=dict)),
                ('sniffing_settings', models.JSONField(blank=True, default=dict)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='vpn.xraycoreserver')),
            ],
            options={
                'ordering': ['port'],
                'unique_together': {('server', 'port'), ('server', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='XrayClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email', models.CharField(help_text='Email for statistics', max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=True)),
                ('flow', models.CharField(blank=True, help_text='VLESS flow control', max_length=50)),
                ('alter_id', models.IntegerField(default=0, help_text='VMess alterId')),
                ('password', models.CharField(blank=True, help_text='Password for Trojan/Shadowsocks', max_length=255)),
                ('total_gb', models.IntegerField(blank=True, help_text='Traffic limit in GB', null=True)),
                ('expiry_time', models.DateTimeField(blank=True, help_text='Account expiration time', null=True)),
                ('up', models.BigIntegerField(default=0, help_text='Upload bytes')),
                ('down', models.BigIntegerField(default=0, help_text='Download bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vpn.xrayinbound')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('inbound', 'user')},
            },
        ),
    ]
