# Generated by Django 5.1.7 on 2025-07-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_remove_xraycoreserver_api_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayInboundProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Xray Inbound (Server View)',
                'verbose_name_plural': 'Xray Inbounds (Server View)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vpn.xrayinbound',),
        ),
        migrations.RemoveField(
            model_name='xraycoreserver',
            name='default_protocol',
        ),
        migrations.RemoveField(
            model_name='xrayinbound',
            name='is_default',
        ),
    ]
