# Generated by Django 5.1.7 on 2025-07-31 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_xrayinboundproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayInboundServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpn.server')),
                ('xray_inbound', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_proxy', to='vpn.xrayinbound')),
            ],
            options={
                'verbose_name': 'Xray Inbound Server',
                'verbose_name_plural': 'Xray Inbound Servers',
            },
            bases=('vpn.server',),
        ),
        migrations.DeleteModel(
            name='XrayInboundProxy',
        ),
    ]
