# Generated by Django 5.1.7 on 2025-07-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0012_xrayinboundserver_delete_xrayinboundproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='xraycoreserver',
            name='client_hostname',
            field=models.CharField(default='127.0.0.1', help_text='Hostname or IP address for client connections (what clients use to connect)', max_length=255),
        ),
    ]
