# Generated by Django 5.1.7 on 2025-08-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0013_add_client_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xraycoreserver',
            name='client_hostname',
            field=models.CharField(default='127.0.0.1', help_text='Hostname or IP address for client connections', max_length=255),
        ),
        migrations.AlterField(
            model_name='xrayinbound',
            name='server_address',
            field=models.CharField(blank=True, help_text='Public server address for client connections', max_length=255),
        ),
    ]
