# Generated by Django 5.1.7 on 2025-08-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0016_add_new_xray_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayServerV2',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vpn.server')),
                ('client_hostname', models.CharField(help_text='Client connection hostname (what users see in their configs)', max_length=255)),
                ('api_address', models.CharField(default='127.0.0.1:10085', help_text='Xray gRPC API address for management', max_length=255)),
                ('api_enabled', models.BooleanField(default=True, help_text='Enable gRPC API for user management')),
                ('stats_enabled', models.BooleanField(default=True, help_text='Enable traffic statistics collection')),
            ],
            options={
                'verbose_name': 'Xray Server v2',
                'verbose_name_plural': 'Xray Servers v2',
            },
            bases=('vpn.server',),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('Outline', 'Outline'), ('Wireguard', 'Wireguard'), ('xray_core', 'Xray Core'), ('xray_v2', 'Xray Server v2')], editable=False, max_length=50),
        ),
        migrations.CreateModel(
            name='ServerInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Whether this inbound is active on the server')),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_config', models.JSONField(blank=True, default=dict, help_text='Server-specific deployment configuration')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_servers', to='vpn.inbound')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployed_inbounds', to='vpn.server')),
            ],
            options={
                'verbose_name': 'Server Inbound Deployment',
                'verbose_name_plural': 'Server Inbound Deployments',
                'ordering': ['server__name', 'inbound__name'],
                'unique_together': {('server', 'inbound')},
            },
        ),
    ]
