# Generated by Django 5.1.7 on 2025-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0017_xrayserverv2_alter_server_server_type_serverinbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pem',
            field=models.TextField(blank=True, help_text="Certificate in PEM format (auto-generated for Let's Encrypt)"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Certificate expiration date (auto-filled after generation)', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='private_key_pem',
            field=models.TextField(blank=True, help_text="Private key in PEM format (auto-generated for Let's Encrypt)"),
        ),
    ]
