# Generated by Django 5.1.7 on 2025-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0018_alter_certificate_certificate_pem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='acme_email',
            field=models.EmailField(blank=True, help_text="Email address for ACME account registration (required for Let's Encrypt)", max_length=254),
        ),
    ]
