# Generated by Django 5.1.7 on 2025-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0019_certificate_acme_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='full_config',
            field=models.JSONField(blank=True, default=dict, help_text='Complete configuration for creating inbound on server (auto-generated if empty)'),
        ),
    ]
