# Generated by Django 5.1.7 on 2025-08-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0020_alter_inbound_full_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XrayConfiguration',
        ),
    ]
