# Generated by Django 5.1.7 on 2025-08-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0021_remove_xray_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbound',
            options={'ordering': ['protocol', 'port'], 'verbose_name': 'Inbound Template', 'verbose_name_plural': 'Inbound Templates'},
        ),
        migrations.RemoveField(
            model_name='inbound',
            name='domain',
        ),
    ]
