# Generated by Django 5.1.7 on 2025-08-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0022_remove_inbound_domain_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiongroup',
            options={'ordering': ['name'], 'verbose_name': 'Subscriptions', 'verbose_name_plural': 'Subscriptions'},
        ),
    ]
