# Generated by Django 5.1.7 on 2025-08-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0023_alter_subscriptiongroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='certificate',
        ),
        migrations.AddField(
            model_name='serverinbound',
            name='certificate',
            field=models.ForeignKey(blank=True, help_text='Certificate for TLS on this specific server (overrides automatic selection)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn.certificate'),
        ),
    ]
