# Generated by Django 5.1.7 on 2025-08-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0024_add_certificate_to_serverinbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_first_name',
            field=models.CharField(blank=True, help_text='First name from Telegram', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_last_name',
            field=models.CharField(blank=True, help_text='Last name from Telegram', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_phone',
            field=models.CharField(blank=True, help_text='Phone number from Telegram (optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (without @)', max_length=255, null=True),
        ),
    ]
