# Generated by Django 5.1.7 on 2025-08-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0025_user_telegram_first_name_user_telegram_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiongroup',
            options={'ordering': ['name'], 'verbose_name': 'XRay-core', 'verbose_name_plural': 'XRay-core'},
        ),
    ]
