# Generated by Django 5.1.7 on 2025-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='api_base_url',
            field=models.URLField(blank=True, default='https://api.telegram.org', help_text='Telegram API base URL (change for local bot API server)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='connection_timeout',
            field=models.IntegerField(default=30, help_text='Connection timeout in seconds'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='proxy_url',
            field=models.URLField(blank=True, help_text='Proxy URL (e.g., http://proxy:8080 or socks5://proxy:1080)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='use_proxy',
            field=models.BooleanField(default=False, help_text='Enable proxy for Telegram API connections'),
        ),
    ]
