# Generated by Django 5.1.7 on 2025-08-14 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_accessrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accessrequest',
            name='telegram_bo_status_cf9310_idx',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Request approved by administrator'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Admin comment for approval'),
        ),
        migrations.AddIndex(
            model_name='accessrequest',
            index=models.Index(fields=['approved', '-created_at'], name='telegram_bo_approve_7ae92d_idx'),
        ),
    ]
