# Generated by Django 5.1.7 on 2025-08-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_accessrequest_telegram_bo_status_cf9310_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotStatus',
        ),
        migrations.RemoveField(
            model_name='botsettings',
            name='welcome_message',
        ),
        migrations.AddField(
            model_name='botsettings',
            name='help_message',
            field=models.TextField(default='📋 Available commands:\n/start - Start conversation\n📊 Access - View your VPN subscriptions\n\nFor support contact administrator.', help_text='Help message sent for unrecognized commands'),
        ),
    ]
