# Generated by Django 5.1.7 on 2025-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_delete_botstatus_remove_botsettings_welcome_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='desired_username',
            field=models.CharField(blank=True, help_text='Desired username for VPN user (defaults to Telegram username)', max_length=150),
        ),
    ]
