# Generated by Django 5.1.7 on 2025-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_accessrequest_desired_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsettings',
            name='help_message',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user_language',
            field=models.CharField(default='en', help_text="User's preferred language (en/ru)", max_length=10),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='user_language',
            field=models.CharField(default='en', help_text="User's preferred language (en/ru)", max_length=10),
        ),
    ]
