# Generated by Django 5.1.7 on 2025-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_accessrequest_selected_existing_user'),
        ('vpn', '0026_alter_subscriptiongroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='selected_inbounds',
            field=models.ManyToManyField(blank=True, help_text='Inbound templates to assign to the user', to='vpn.inbound'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='selected_subscription_groups',
            field=models.ManyToManyField(blank=True, help_text='Subscription groups to assign to the user', to='vpn.subscriptiongroup'),
        ),
    ]
